# Introducción a pandas para Ingeniería de Datos

**Materia:** Big Data  
**Nivel:** Primer año de Tecnicatura Superior en Desarrollo de Software Multiplataforma.  
**Institución:** Instituto Politecnico Formosa.

## 1. ¿Qué hace una persona de ingeniería de datos?

Una persona de ingeniería de datos construye y mantiene procesos para que los datos lleguen desde sus **fuentes** hasta las personas o sistemas que los necesitan. Por ejemplo, desde archivos CSV, APIs, sensores o una base de datos hacia un tablero, un modelo de machine learning o un reporte.

Un flujo típico sigue estas etapas:

1. **Extraer:** obtener datos desde una fuente.
2. **Validar y limpiar:** detectar errores, valores faltantes y formatos inconsistentes.
3. **Transformar:** preparar los datos para responder una necesidad del negocio.
4. **Integrar:** combinar fuentes relacionadas.
5. **Publicar:** guardar el resultado para que otros puedan usarlo.

`pandas` es especialmente útil para aprender y prototipar las etapas 2, 3 y 4 con conjuntos de datos que caben en la memoria del equipo.

## 2. ¿Qué es pandas?

`pandas` es una biblioteca de Python orientada al análisis y la manipulación de datos estructurados. Su unidad principal es el **DataFrame**, una tabla con filas y columnas, similar a una hoja de cálculo o al resultado de una consulta SQL.

El alias `pd` es una convención ampliamente usada. Permite reconocer de inmediato que una operación pertenece a pandas.

**Cuándo elegir pandas:** exploración, limpieza, preparación de archivos, automatizaciones pequeñas y pruebas de lógica de transformación. Para datos que no caben en memoria o procesamiento distribuido, se usan herramientas como Spark, pero muchos conceptos se mantienen.

In [53]:
import pandas as pd

dias_semana = ["Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado", "Domingo"] 

pd.Series(dias_semana)

0        Lunes
1       Martes
2    Miercoles
3       Jueves
4      Viernes
5       Sabado
6      Domingo
dtype: str

In [54]:
diccionario ={
    "a":1,
    "b":2,
    "c":3,
}

serie = pd.Series(data=diccionario, index = diccionario.keys())

serie

a    1
b    2
c    3
dtype: int64

## 3. Estructuras principales: Series y DataFrame

Una **Series** es una sola columna de datos con un índice. Puede representar, por ejemplo, los precios de una tabla o los dias de la semana. 

```python
    dias_semana = ["Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado", "Domingo"] 
    pd.Series(dias_semana)
```

Un **DataFrame** es una colección de Series que comparten el mismo índice. Cada fila suele representar una observación o evento: una venta, un estudiante, una lectura de sensor o una visita web.

| Concepto | Ejemplo | Equivalencia aproximada |
| --- | --- | --- |
| Fila | Una venta realizada | Registro de una tabla SQL |
| Columna | `fecha_venta` | Campo de una tabla SQL |
| Índice | Identificador interno de la fila | No siempre tiene equivalente directo |
| DataFrame | Tabla de ventas | Tabla o resultado de una consulta |

En proyectos reales, antes de transformar un DataFrame hay que identificar el significado de cada fila, la clave que la identifica y el tipo esperado de cada columna. Esto forma parte del **contrato de datos**.

## 4. Lectura de datos: la etapa de extracción

Los métodos de lectura convierten una fuente externa en un DataFrame. El método adecuado depende del formato de origen.

| Método | Se usa para | Aspectos a revisar |
| --- | --- | --- |
| `pd.read_csv()` | Archivos CSV o texto delimitado | Separador, codificación, encabezados y tipos |
| `pd.read_excel()` | Hojas de cálculo Excel | Hoja a leer y celdas de encabezado |
| `pd.read_json()` | Archivos o respuestas JSON | Estructura anidada y orientación de los datos |
| `pd.read_sql()` | Consultas a bases de datos SQL | Consulta, conexión y volumen de datos |
| `pd.read_parquet()` | Archivos Parquet | Columnas necesarias y compatibilidad del formato |

In [55]:
ventas = pd.read_csv("ventas.csv") #C:/Users/IPF-2026/Desktop/TRABAJO-IPF/2DO-CUATRIMESTRE/big-data/big-data/03-09-2026/vetnas.csv
ventas

,id_venta,id_cliente,cliente,ciudad,categoria,producto,cantidad,importe,metodo_pago,fecha
0,VTA-1081,CLI-003,Juan Perez,Buenos Aires,indumentaria,Buzo Canguro,1,60751.90,Transferencia,03/06/2024
1,VTA-1142,CLI-008,Lucia Morales,Rosario,Hogar,Cafetera Express,1,5523.75,EFECTIVO,2024-03-24
2,VTA-1031,CLI-007,maria lopez,Buenos Aires,Electrónica,Auriculares Bluetooth,1,131699.70,EFECTIVO,2024-04-02
3,VTA-1029,CLI-005,JUAN PEREZ,Córdoba,INDUMENTARIA,Campera Invierno,4,344514.47,EFECTIVO,2024/02/14
4,VTA-1118,CLI-003,MARTIN RODRIGUEZ,Buenos Aires,hogar,Aspiradora Robot,1,31963.24,tarjeta de debito,18/05/2024
...,...,...,...,...,...,...,...,...,...,...
150,VTA-1071,CLI-007,martin rodriguez,Buenos Aires,ELECTRONICA,Mouse Gamer,1,NaN,Mercado Pago,NaN
151,VTA-1106,CLI-007,ANA FERNANDEZ,BUENOS AIRES,Hogar,Aspiradora Robot,2,55876.68,EFECTIVO,2024/04/27
152,VTA-1014,CLI-005,MARTIN RODRIGUEZ,mendoza,Hogar,Cafetera Express,1,0.00,tarjeta de debito,2024/05/18
153,VTA-1092,CLI-007,JUAN PEREZ,Córdoba,Electrónica,Monitor 24,5,555094.68,Tarjeta de Crédito,03/03/2024
154,VTA-1102,CLI-003,JUAN PEREZ,Rosario,NaN,Lámpara LED,3,263152.11,Mercado Pago,12/01/2024

In [56]:
ventas_db.head()

,index,id_venta,id_cliente,cliente,ciudad,categoria,producto,cantidad,importe,metodo_pago,fecha
0,0,VTA-1081,CLI-003,Juan Perez,Buenos Aires,indumentaria,Buzo Canguro,1,60751.90,Transferencia,03/06/2024
1,1,VTA-1142,CLI-008,Lucia Morales,Rosario,Hogar,Cafetera Express,1,5523.75,EFECTIVO,2024-03-24
2,2,VTA-1031,CLI-007,maria lopez,Buenos Aires,Electrónica,Auriculares Bluetooth,1,131699.70,EFECTIVO,2024-04-02
3,3,VTA-1029,CLI-005,JUAN PEREZ,Córdoba,INDUMENTARIA,Campera Invierno,4,344514.47,EFECTIVO,2024/02/14
4,4,VTA-1118,CLI-003,MARTIN RODRIGUEZ,Buenos Aires,hogar,Aspiradora Robot,1,31963.24,tarjeta de debito,18/05/2024

In [58]:
ventas_db.tail(5)

,index,id_venta,id_cliente,cliente,ciudad,categoria,producto,cantidad,importe,metodo_pago,fecha
150,150,VTA-1071,CLI-007,martin rodriguez,Buenos Aires,ELECTRONICA,Mouse Gamer,1,NaN,Mercado Pago,NaN
151,151,VTA-1106,CLI-007,ANA FERNANDEZ,BUENOS AIRES,Hogar,Aspiradora Robot,2,55876.68,EFECTIVO,2024/04/27
152,152,VTA-1014,CLI-005,MARTIN RODRIGUEZ,mendoza,Hogar,Cafetera Express,1,0.00,tarjeta de debito,2024/05/18
153,153,VTA-1092,CLI-007,JUAN PEREZ,Córdoba,Electrónica,Monitor 24,5,555094.68,Tarjeta de Crédito,03/03/2024
154,154,VTA-1102,CLI-003,JUAN PEREZ,Rosario,NaN,Lámpara LED,3,263152.11,Mercado Pago,12/01/2024

In [61]:
ventas_db.shape

(155, 11)

In [62]:
ventas_db.info()

<class 'pandas.DataFrame'>
RangeIndex: 155 entries, 0 to 154
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   index        155 non-null    int64
 1   id_venta     155 non-null    str
 2   id_cliente   155 non-null    str
 3   cliente      155 non-null    str
 4   ciudad       144 non-null    str
 5   categoria    148 non-null    str
 6   producto     155 non-null    str
 7   cantidad     155 non-null    int64
 8   importe      147 non-null    float64
 9   metodo_pago  150 non-null    str
 10  fecha        149 non-null    str
dtypes: float64(1), int64(2), str(8)
memory usage: 13.4 KB

In [63]:
ventas_db.describe()

            index    cantidad       importe
count  155.000000  155.000000  1.470000e+02
mean    77.000000    1.819355  1.309947e+05
std     44.888751    1.505276  1.743561e+05
min      0.000000    1.000000 -2.277457e+05
25%     38.500000    1.000000  5.416902e+04
50%     77.000000    1.000000  9.713393e+04
75%    115.500000    2.000000  1.412125e+05
max    154.000000   10.000000  1.380986e+06

In [65]:
ventas_db["categoria"].value_counts()

categoria
alimentos       18
INDUMENTARIA    15
Hogar           14
indumentaria    13
ALIMENTOS       13
HOGAR           11
Electrónica     10
hogar           10
ELECTRONICA     10
 Electrónica    10
Alimentos        9
Indumentaria     8
electronica      7
Name: count, dtype: int64

In [67]:
ventas_db[["cantidad", "producto"]]

     cantidad               producto
0           1           Buzo Canguro
1           1       Cafetera Express
2           1  Auriculares Bluetooth
3           4       Campera Invierno
4           1       Aspiradora Robot
..        ...                    ...
150         1            Mouse Gamer
151         2       Aspiradora Robot
152         1       Cafetera Express
153         5             Monitor 24
154         3            Lámpara LED

[155 rows x 2 columns]

In [76]:
ventas_db[ventas_db["cantidad"] ==5]

,index,id_venta,id_cliente,cliente,ciudad,categoria,producto,cantidad,importe,metodo_pago,fecha
25,25,VTA-1131,CLI-009,Juan Perez,Rosario,Indumentaria,Remera Algodón,5,142581.64,EFECTIVO,2024/05/20
153,153,VTA-1092,CLI-007,JUAN PEREZ,Córdoba,Electrónica,Monitor 24,5,555094.68,Tarjeta de Crédito,03/03/2024

In [78]:
ventas_db.isnull().sum()

index           0
id_venta        0
id_cliente      0
cliente         0
ciudad         11
categoria       7
producto        0
cantidad        0
importe         8
metodo_pago     5
fecha           6
dtype: int64

In [84]:
ventas[ventas.duplicated()]

,id_venta,id_cliente,cliente,ciudad,categoria,producto,cantidad,importe,metodo_pago,fecha
71,VTA-1040,CLI-005,Maria Lopez,rosario,Alimentos,Café en Grano 1kg,1,35543.83,EFECTIVO,2024/01/06
77,VTA-1012,CLI-003,JUAN PEREZ,mendoza,HOGAR,Lámpara LED,1,136111.11,Mercado Pago,25/01/2024
92,VTA-1005,CLI-003,MARIA LOPEZ,LA PLATA,Electrónica,Mouse Gamer,2,92509.23,tarjeta de debito,2024-01-29
129,VTA-1025,CLI-007,maria lopez,Buenos Aires,electronica,Auriculares Bluetooth,3,143372.18,Mercado Pago,2024/01/28
148,VTA-1078,CLI-001,maria lopez,NaN,alimentos,Aceite de Oliva 500ml,1,130679.61,Tarjeta de Crédito,08/02/2024

In [85]:
ventas.to_csv("nuevo_dataset.csv")

## 5. Inspección inicial: conocer antes de cambiar

Al recibir un conjunto de datos, primero se explora. Esta revisión permite descubrir columnas inesperadas, tipos erróneos, datos ausentes y posibles problemas de calidad.

| Método o atributo | Para qué se usa |
| --- | --- |
| `df.head()` | Ver las primeras filas y reconocer la estructura rápidamente. |
| `df.tail()` | Revisar las últimas filas; útil para detectar cambios al final de un archivo. |
| `df.shape` | Conocer la cantidad de filas y columnas. |
| `df.columns` | Listar los nombres de las columnas. |
| `df.info()` | Revisar tipos de datos, valores no nulos y uso de memoria. |
| `df.describe()` | Obtener estadísticas descriptivas de columnas numéricas. |
| `df['columna'].value_counts()` | Contar la frecuencia de cada categoría. |

En ingeniería de datos, estas operaciones responden preguntas de calidad: ¿cuántos registros llegaron?, ¿cuántos valores faltan?, ¿la columna fecha realmente es fecha?, ¿apareció una categoría nueva?

In [ ]:
import sqlite3 as sql

conn = sql.connect("ventas.db")

ventas_db = pd.read_sql(con=conn, sql="SELECT * FROM ventas")

ventas_db

,index,id_venta,id_cliente,cliente,ciudad,categoria,producto,cantidad,importe,metodo_pago,fecha
0,0,VTA-1081,CLI-003,Juan Perez,Buenos Aires,indumentaria,Buzo Canguro,1,60751.90,Transferencia,03/06/2024
1,1,VTA-1142,CLI-008,Lucia Morales,Rosario,Hogar,Cafetera Express,1,5523.75,EFECTIVO,2024-03-24
2,2,VTA-1031,CLI-007,maria lopez,Buenos Aires,Electrónica,Auriculares Bluetooth,1,131699.70,EFECTIVO,2024-04-02
3,3,VTA-1029,CLI-005,JUAN PEREZ,Córdoba,INDUMENTARIA,Campera Invierno,4,344514.47,EFECTIVO,2024/02/14
4,4,VTA-1118,CLI-003,MARTIN RODRIGUEZ,Buenos Aires,hogar,Aspiradora Robot,1,31963.24,tarjeta de debito,18/05/2024
...,...,...,...,...,...,...,...,...,...,...,...
150,150,VTA-1071,CLI-007,martin rodriguez,Buenos Aires,ELECTRONICA,Mouse Gamer,1,NaN,Mercado Pago,NaN
151,151,VTA-1106,CLI-007,ANA FERNANDEZ,BUENOS AIRES,Hogar,Aspiradora Robot,2,55876.68,EFECTIVO,2024/04/27
152,152,VTA-1014,CLI-005,MARTIN RODRIGUEZ,mendoza,Hogar,Cafetera Express,1,0.00,tarjeta de debito,2024/05/18
153,153,VTA-1092,CLI-007,JUAN PEREZ,Córdoba,Electrónica,Monitor 24,5,555094.68,Tarjeta de Crédito,03/03/2024
154,154,VTA-1102,CLI-003,JUAN PEREZ,Rosario,NaN,Lámpara LED,3,263152.11,Mercado Pago,12/01/2024

## 6. Selección y filtrado: trabajar con la parte necesaria

Seleccionar columnas reduce ruido y hace explícito qué datos necesita una transformación. Filtrar filas permite conservar solo los registros que cumplen una condición.

| Expresión o método | Para qué se usa |
| --- | --- |
| `df['columna']` | Seleccionar una columna como Series. |
| `df[['a', 'b']]` | Seleccionar varias columnas como DataFrame. |
| `df.loc[filas, columnas]` | Seleccionar por etiquetas o condiciones claras. |
| `df.iloc[filas, columnas]` | Seleccionar por posición numérica. |
| `df.query()` | Filtrar con una expresión legible, especialmente en condiciones largas. |

Ejemplo: conservar ventas con importe positivo.

```python
ventas_validas = ventas.loc[ventas['importe'] > 0, ['id_venta', 'fecha', 'importe']]
```

Usar `.loc` hace visible tanto la condición aplicada como las columnas que se conservarán.

## 7. Calidad y limpieza de datos

Los datos reales pueden tener campos vacíos, filas repetidas, errores tipográficos o tipos incorrectos. Limpiar no significa borrar todo lo extraño: significa aplicar una regla de negocio conocida y dejarla documentada.

| Método | Para qué se usa |
| --- | --- |
| `df.isna()` | Identificar valores faltantes. |
| `df.isna().sum()` | Contar valores faltantes por columna. |
| `df.dropna()` | Eliminar filas o columnas con valores faltantes según una regla. |
| `df.fillna()` | Reemplazar valores faltantes por un valor definido. |
| `df.duplicated()` | Detectar filas duplicadas. |
| `df.drop_duplicates()` | Eliminar duplicados, opcionalmente usando columnas clave. |
| `df.rename()` | Normalizar o corregir nombres de columnas. |
| `df.astype()` | Convertir una columna a un tipo específico. |
| `pd.to_datetime()` | Convertir texto u otros valores a fechas. |

Una práctica importante es medir el efecto de la limpieza: comparar `df.shape` antes y después, y registrar cuántos valores o filas se modificaron.

## 8. Transformación: convertir datos en información útil

Transformar consiste en crear, modificar o reorganizar columnas para responder una necesidad concreta. Por ejemplo, derivar el año de una fecha, estandarizar códigos o calcular el importe total de una venta.

| Método o acceso | Para qué se usa |
| --- | --- |
| `df.assign()` | Crear columnas nuevas de forma encadenable. |
| `df.sort_values()` | Ordenar filas por una o más columnas. |
| `df.replace()` | Sustituir valores específicos y normalizar categorías. |
| `df['texto'].str` | Aplicar operaciones de texto: mayúsculas, reemplazos, extracción, etc. |
| `df['fecha'].dt` | Extraer partes de fechas: año, mes, día o día de la semana. |

Se prefieren las operaciones **vectorizadas** de pandas, como sumar columnas directamente, porque trabajan sobre toda la columna y suelen ser más claras y eficientes que recorrer fila por fila.

## 9. Agrupación y resumen: responder preguntas

Las agregaciones reducen muchos registros a indicadores útiles. Por ejemplo: total vendido por ciudad, cantidad de eventos por día o promedio de calificaciones por curso.

| Método | Para qué se usa |
| --- | --- |
| `df.groupby()` | Formar grupos según una o más columnas. |
| `.sum()` | Calcular sumas. |
| `.mean()` | Calcular promedios. |
| `.count()` | Contar valores no nulos. |

## 10. Integración de fuentes: combinar tablas

Es frecuente que la información esté separada en distintas tablas. Por ejemplo, podemos tener una tabla con las ventas realizadas y otra con la información de los clientes.

Antes de combinarlas, debemos identificar cuál es la **clave** que relaciona ambas tablas. En este caso, podría ser `id_cliente`.

| Método        | Para qué se usa                                                                            |
| ------------- | ------------------------------------------------------------------------------------------ |
| `pd.merge()`  | Unir columnas de dos DataFrames utilizando una clave, de forma similar a un `JOIN` de SQL. |
| `df.join()`   | Unir DataFrames principalmente utilizando sus índices.                                     |
| `pd.concat()` | Combinar DataFrames apilándolos por filas o columnas.                                      |

---

### `pd.merge()`

Supongamos que tenemos estos dos DataFrames:

Visualmente:

**clientes**

| id_cliente | nombre |
| ---------- | ------ |
| 1          | Ana    |
| 2          | Carlos |
| 3          | Lucía  |

**ventas**

| id_venta | id_cliente | total |
| -------- | ---------- | ----- |
| 101      | 1          | 15000 |
| 102      | 2          | 22000 |
| 103      | 4          | 18000 |

Ambas tablas tienen la columna `id_cliente`, por lo tanto podemos utilizarla como clave para relacionarlas.

### `inner`

Conserva únicamente los clientes que aparecen en ambas tablas.


```python
resultado = pd.merge(
    ventas,
    clientes,
    on="id_cliente",
    how="inner"
)

```

Resultado:

```text
   id_venta  id_cliente  total  nombre
0       101           1  15000     Ana
1       102           2  22000  Carlos
```

El cliente `3` no aparece porque no tiene ventas, mientras que el cliente `4` tampoco aparece porque no existe en la tabla `clientes`.

---

### `left`

Conserva todas las filas del DataFrame ubicado a la izquierda.


```python
resultado = pd.merge(
    ventas,
    clientes,
    on="id_cliente",
    how="left"
)
```

Resultado:

```text
   id_venta  id_cliente  total  nombre
0       101           1  15000     Ana
1       102           2  22000  Carlos
2       103           4  18000     NaN
```

Como `ventas` está a la izquierda, se conservan todas sus filas.

El `id_cliente = 4` no tiene información asociada en la tabla `clientes`, por eso aparece `NaN` en `nombre`.

Este tipo de unión es muy útil cuando queremos conservar todos nuestros registros principales aunque no encontremos información relacionada en otra tabla.

---

### `right`

Conserva todas las filas del DataFrame ubicado a la derecha.


```python
resultado = pd.merge(
    ventas,
    clientes,
    on="id_cliente",
    how="right"
)
```

## 11. Escritura de resultados: la etapa de publicación

Cuando una transformación está validada, el resultado se guarda en un formato que pueda consumir el siguiente paso del proceso.

| Método | Para qué se usa |
| --- | --- |
| `df.to_csv()` | Exportar una tabla a CSV, práctico para interoperabilidad. |
| `df.to_excel()` | Generar un archivo Excel para usuarios de negocio. |
| `df.to_parquet()` | Guardar datos tabulares de forma eficiente, conservando tipos. |
| `df.to_sql()` | Escribir datos en una tabla de base de datos. |

Ejemplo conceptual:

```python
resumen.to_parquet('resumen_ventas.parquet', index=False)
```

El parámetro `index=False` evita guardar el índice técnico como una columna adicional cuando no forma parte del dato de negocio.

## 12. Buenas prácticas para empezar

1. **Inspeccionar antes de transformar.** Revisar estructura, tipos y faltantes antes de escribir reglas.
2. **No modificar la fuente original.** Conservar los datos de entrada y producir una salida nueva.
3. **Usar nombres claros.** Preferir `ventas_limpias` a `df2`.
4. **Validar cada etapa.** Controlar filas, columnas, nulos y duplicados después de operaciones importantes.
5. **Documentar supuestos.** Explicar por qué se eliminaron filas o cómo se rellenaron faltantes.
6. **Elegir tipos correctos.** Fechas como fechas, importes como números y categorías como texto o tipo categórico.

### Idea clave

Aprender pandas no consiste solo en manipular tablas. Consiste en desarrollar criterio para entender la calidad, el significado y el recorrido de los datos. Ese criterio es la base para trabajar después con bases de datos, procesos ETL/ELT y plataformas de Big Data.